### PR TITLE
Documentation

### LINKED ISSUE #4: Documentation update
We should update the documentation to allow any new people or external collaborators to use this code.

### PR DESCRIPTION
**Pull request by akojamil**
Updating the documentation to help ease new students getting started with analyzing data in the lab.

### CODE REVIEW

**Comment by allan-ylsung** [comment]
In della.md, maybe we could put a link to the Notion page where the instructions already exist?

**Comment by akojamil** [comment]
The problem is that the Notion page is private, so we should move the page from Notion to here. So I recommend that we move all code-related stuff to a single place.

**Comment by allan-ylsung** [comment]
Okay understand. I can do it later.

**Comment by allan-ylsung** [comment]
I adapted the instructions on the Notion page. Please take a look at della.md and let me know if it looks okay.

**Comment by akojamil** [comment]
Looks good to me. I think we can merge for now and add more details as we go. What do you think?

**Pull request merged**
