### PR TITLE
5 rename sipm and dataset classes

### LINKED ISSUE #5: Rename SiPM and Dataset classes
Rename class SiPM to WaveformAnalyzer and class Dataset to WaveformDataset. Modify all files accordingly.

### PR DESCRIPTION
**Pull request by allan-ylsung**
Renamed SiPM and Dataset and tested the three analysis notebooks (calibration.ipynb, spectrum.ipynb, triplet_lifetime.ipynb) as well as the job submission code (analysis.py, submit.py, submit.ipynb, io.ipynb).

A few things:
1. I didn't test analysis.ipynb, breakdown.ipynb, and demo.ipynb. Are those still being used, @akojamil?
2. I had to install pytables and change the anaconda version at submit.py line 76 for the job submission to succeed. The former issue seems to be a one-time thing, but the latter one is more tricky. The available anaconda versions seem to change every time I log in. Then I had to modify the version in the code. Is there any way to detect available versions automatically?

### CODE REVIEW

**Comment by akojamil** [comment]
I think those notebooks are obsolete and we can remove analysis.ipynb, demo.ipynb, breakdown.ipynb. @allan-ylsung can you add that to this pull request?

**Comment by akojamil** [comment]
To your second point regarding anaconda: this is strange since the availability of the modules on the cluster shouldn't depend on when and how you log in. 

We can prevent this by using our own conda installation, but should add this to the installation instructions.

**Comment by akojamil** [comment]
I added some text here for how to do that: https://github.com/darkside-princeton/sipm-analysis/commit/357bc2157afe5d54b48d365ca368299382b35594

**Comment by akojamil** [comment]
Now that I think about it, we might want to rename the subdirs as well. I would suggest 

recon --> exe 
io --> recon

What do you think @allan-ylsung?

**Comment by allan-ylsung** [comment]
> I think those notebooks are obsolete and we can remove analysis.ipynb, demo.ipynb, breakdown.ipynb. @allan-ylsung can you add that to this pull request?

Removed.

**Comment by allan-ylsung** [comment]
> To your second point regarding anaconda: this is strange since the availability of the modules on the cluster shouldn't depend on when and how you log in. 

We can prevent this by using our own conda installation, but should add this to the installation instructions.  

Updated conda command. Notebooks were tested after miniconda was installed following the instructions in doc/installation.md under documentation branch.

**Comment by allan-ylsung** [comment]
Changed subdir names. Ready to merge.

**Review by akojamil — APPROVED** [review]

**Pull request merged**
